package braxxi.kursach.client.ui;

import braxxi.kursach.commons.entity.EstateEntity;
import braxxi.kursach.commons.model.SystemDictionary;

import javax.swing.*;
import java.awt.*;
import java.math.BigDecimal;

import static braxxi.kursach.client.ui.UIUtils.*;

public class EstateView {
	private JFormattedTextField formattedTextFieldTotalArea;
	private JFormattedTextField formattedTextFieldLivingArea;
	private JFormattedTextField formattedTextFieldFloor;
	private JFormattedTextField formattedTextFieldDistanceToMetro;
	private JTextArea textAreaDescription;
	private JPanel rootPanel;
	private JFormattedTextField formattedTextFieldRooms;
	private JTextField textFieldContacts;
	private JFormattedTextField formattedTextFieldKitchenArea;
	private JFormattedTextField formattedTextFieldFloors;
	private JComboBox comboBoxDistrict;
	private JFormattedTextField formattedTextFieldPrice;
	private JLabel descriptionLabel;
	private JLabel contactsLabel;
	private JScrollPane descriptionScrollPane;
	private JLabel priceLabel;
	private JLabel metroLabel;
	private JLabel floorsLabel;
	private JLabel floorLabel;

	private SystemDictionary districts;

	public void init(SystemDictionary districts) {
		this.districts = districts;

		final DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel(districts.getItems().toArray());
		comboBoxDistrict.setModel(comboBoxModel);

		formattedTextFieldTotalArea.setFormatterFactory(createBigDecimalFormatter());
		formattedTextFieldLivingArea.setFormatterFactory(createBigDecimalFormatter());
		formattedTextFieldKitchenArea.setFormatterFactory(createBigDecimalFormatter());
		formattedTextFieldPrice.setFormatterFactory(createBigDecimalFormatter());

		formattedTextFieldFloor.setFormatterFactory(createIntFormatter());
		formattedTextFieldFloors.setFormatterFactory(createIntFormatter());
		formattedTextFieldDistanceToMetro.setFormatterFactory(createIntFormatter());
		formattedTextFieldRooms.setFormatterFactory(createIntFormatter());
	}

	public JPanel getRootPanel() {
		return this.rootPanel;
	}

	public void setData(EstateEntity data) {
		comboBoxDistrict.setRenderer(new DictionaryItemDefaultListCellRenderer());
		comboBoxDistrict.setSelectedItem(districts.findById(data.getDistrictId()));

		formattedTextFieldTotalArea.setValue(data.getTotalArea());
		formattedTextFieldLivingArea.setValue(data.getLivingArea());
		formattedTextFieldKitchenArea.setValue(data.getKitchenArea());

		formattedTextFieldFloor.setValue(data.getFloor());
		formattedTextFieldFloors.setValue(data.getFloors());

		formattedTextFieldDistanceToMetro.setValue(data.getDistanceToMetro());

		textAreaDescription.setText(data.getDescription());
		formattedTextFieldRooms.setValue(data.getRooms());
		textFieldContacts.setText(data.getContacts());

		formattedTextFieldPrice.setValue(data.getPrice());
	}

	public void getData(EstateEntity data) {
		data.setDistrictId(getSelectedDictionaryItemId(comboBoxDistrict));

		data.setTotalArea((BigDecimal) formattedTextFieldTotalArea.getValue());
		data.setLivingArea((BigDecimal) formattedTextFieldLivingArea.getValue());
		data.setKitchenArea((BigDecimal) formattedTextFieldKitchenArea.getValue());

		data.setFloor((Integer) formattedTextFieldFloor.getValue());
		data.setFloors((Integer) formattedTextFieldFloors.getValue());

		data.setDistanceToMetro((Integer) formattedTextFieldDistanceToMetro.getValue());

		data.setDescription(textAreaDescription.getText());
		data.setRooms((Integer) formattedTextFieldRooms.getValue());
		data.setContacts(textFieldContacts.getText());

		data.setPrice((BigDecimal) formattedTextFieldPrice.getValue());
	}

	public void prepareEstimateView() {
		//hideMe(floorLabel, formattedTextFieldFloor);
		hideMe(floorsLabel, formattedTextFieldFloors);
		hideMe(metroLabel, formattedTextFieldDistanceToMetro);
		hideMe(priceLabel, formattedTextFieldPrice);
		hideMe(contactsLabel, textFieldContacts);
		hideMe(descriptionLabel, textAreaDescription);
		descriptionScrollPane.setVisible(false);
	}

	private void hideMe(JLabel descriptionLabel, JComponent component) {
		descriptionLabel.setVisible(false);
		component.setVisible(false);
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		rootPanel = new JPanel();
		rootPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(11, 2, new Insets(0, 0, 0, 0), -1, -1));
		metroLabel = new JLabel();
		metroLabel.setText("До метро");
		rootPanel.add(metroLabel, new com.intellij.uiDesigner.core.GridConstraints(7, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		formattedTextFieldDistanceToMetro = new JFormattedTextField();
		rootPanel.add(formattedTextFieldDistanceToMetro, new com.intellij.uiDesigner.core.GridConstraints(7, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		formattedTextFieldFloor = new JFormattedTextField();
		rootPanel.add(formattedTextFieldFloor, new com.intellij.uiDesigner.core.GridConstraints(5, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		floorLabel = new JLabel();
		floorLabel.setText("Этаж");
		rootPanel.add(floorLabel, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		formattedTextFieldLivingArea = new JFormattedTextField();
		rootPanel.add(formattedTextFieldLivingArea, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		final JLabel label1 = new JLabel();
		label1.setText("Жилая площадь");
		rootPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		formattedTextFieldTotalArea = new JFormattedTextField();
		rootPanel.add(formattedTextFieldTotalArea, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		final JLabel label2 = new JLabel();
		label2.setText("Общая площадь");
		rootPanel.add(label2, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final JLabel label3 = new JLabel();
		label3.setText("Район");
		rootPanel.add(label3, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(150, -1), null, null, 0, false));
		descriptionLabel = new JLabel();
		descriptionLabel.setText("Описание");
		rootPanel.add(descriptionLabel, new com.intellij.uiDesigner.core.GridConstraints(10, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		descriptionScrollPane = new JScrollPane();
		rootPanel.add(descriptionScrollPane, new com.intellij.uiDesigner.core.GridConstraints(10, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
		textAreaDescription = new JTextArea();
		textAreaDescription.setLineWrap(false);
		textAreaDescription.setMinimumSize(new Dimension(0, 50));
		textAreaDescription.setWrapStyleWord(true);
		descriptionScrollPane.setViewportView(textAreaDescription);
		final JLabel label4 = new JLabel();
		label4.setText("Комнат");
		rootPanel.add(label4, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		formattedTextFieldRooms = new JFormattedTextField();
		rootPanel.add(formattedTextFieldRooms, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		contactsLabel = new JLabel();
		contactsLabel.setText("Контакты");
		rootPanel.add(contactsLabel, new com.intellij.uiDesigner.core.GridConstraints(9, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		textFieldContacts = new JTextField();
		rootPanel.add(textFieldContacts, new com.intellij.uiDesigner.core.GridConstraints(9, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		final JLabel label5 = new JLabel();
		label5.setText("Площадь кухни");
		rootPanel.add(label5, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		formattedTextFieldKitchenArea = new JFormattedTextField();
		rootPanel.add(formattedTextFieldKitchenArea, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		floorsLabel = new JLabel();
		floorsLabel.setText("Всего этажей");
		rootPanel.add(floorsLabel, new com.intellij.uiDesigner.core.GridConstraints(6, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		formattedTextFieldFloors = new JFormattedTextField();
		rootPanel.add(formattedTextFieldFloors, new com.intellij.uiDesigner.core.GridConstraints(6, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		comboBoxDistrict = new JComboBox();
		rootPanel.add(comboBoxDistrict, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		priceLabel = new JLabel();
		priceLabel.setText("Стоимость");
		rootPanel.add(priceLabel, new com.intellij.uiDesigner.core.GridConstraints(8, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		formattedTextFieldPrice = new JFormattedTextField();
		rootPanel.add(formattedTextFieldPrice, new com.intellij.uiDesigner.core.GridConstraints(8, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return rootPanel;
	}
}
