package braxxi.kursach.client.ui;

import braxxi.kursach.commons.model.DictionaryItem;
import braxxi.kursach.commons.model.SearchEstate;
import braxxi.kursach.commons.model.SystemDictionary;

import javax.swing.*;
import java.awt.*;
import java.math.BigDecimal;
import java.util.ArrayList;

import static braxxi.kursach.client.ui.UIUtils.*;

public class SearchEstateView {
	private JFormattedTextField formattedTextFieldTotalAreaTo;
	private JPanel rootPanel;
	private JComboBox comboBoxDistrict;
	private JFormattedTextField formattedTextFieldTotalAreaFrom;
	private JFormattedTextField formattedTextFieldLivingFrom;
	private JFormattedTextField formattedTextFieldLivingAreaTo;
	private JFormattedTextField formattedTextFieldKitchenAreaFrom;
	private JFormattedTextField formattedTextFieldKitchenAreaTo;
	private JFormattedTextField formattedTextFieldRoomsFrom;
	private JFormattedTextField formattedTextFieldRoomsTo;
	private JFormattedTextField formattedTextFieldFloorFrom;
	private JFormattedTextField formattedTextFieldFloorTo;

	public void init(SystemDictionary districts) {
		final java.util.List<DictionaryItem> items = new ArrayList(districts.getItems());
		items.add(0, new DictionaryItem(null, " "));
		final DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel(items.toArray());
		comboBoxDistrict.setModel(comboBoxModel);
		comboBoxDistrict.setRenderer(new DictionaryItemDefaultListCellRenderer());

		formattedTextFieldTotalAreaFrom.setFormatterFactory(createBigDecimalFormatter());
		formattedTextFieldTotalAreaTo.setFormatterFactory(createBigDecimalFormatter());

		formattedTextFieldLivingFrom.setFormatterFactory(createBigDecimalFormatter());
		formattedTextFieldLivingAreaTo.setFormatterFactory(createBigDecimalFormatter());

		formattedTextFieldKitchenAreaFrom.setFormatterFactory(createBigDecimalFormatter());
		formattedTextFieldKitchenAreaTo.setFormatterFactory(createBigDecimalFormatter());

		formattedTextFieldRoomsFrom.setFormatterFactory(createIntFormatter());
		formattedTextFieldRoomsTo.setFormatterFactory(createIntFormatter());

		formattedTextFieldFloorFrom.setFormatterFactory(createIntFormatter());
		formattedTextFieldFloorTo.setFormatterFactory(createIntFormatter());
	}

	public JPanel getRootPanel() {
		return this.rootPanel;
	}

	public void setData(SearchEstate data) {
	}

	public SearchEstate getData(SearchEstate data) {
		data.setDistrictId(getSelectedDictionaryItemId(comboBoxDistrict));

		data.setTotalAreaFrom((BigDecimal) formattedTextFieldTotalAreaFrom.getValue());
		data.setTotalAreaTo((BigDecimal) formattedTextFieldTotalAreaTo.getValue());

		data.setLivingAreaFrom((BigDecimal) formattedTextFieldLivingFrom.getValue());
		data.setLivingAreaTo((BigDecimal) formattedTextFieldLivingAreaTo.getValue());

		data.setKitchenAreaFrom((BigDecimal) formattedTextFieldKitchenAreaFrom.getValue());
		data.setKitchenAreaTo((BigDecimal) formattedTextFieldKitchenAreaTo.getValue());

		data.setRoomsFrom((Integer) formattedTextFieldRoomsFrom.getValue());
		data.setRoomsTo((Integer) formattedTextFieldRoomsTo.getValue());

		data.setFloorFrom((Integer) formattedTextFieldFloorFrom.getValue());
		data.setFloorTo((Integer) formattedTextFieldFloorTo.getValue());

		return data;
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		rootPanel = new JPanel();
		rootPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(7, 4, new Insets(0, 0, 0, 0), -1, -1));
		rootPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Параметры поиска"));
		final JLabel label1 = new JLabel();
		label1.setText("Район");
		rootPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
		rootPanel.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(6, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
		final JLabel label2 = new JLabel();
		label2.setText("Комнат, от");
		rootPanel.add(label2, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final JLabel label3 = new JLabel();
		label3.setText("Этаж, от");
		rootPanel.add(label3, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		comboBoxDistrict = new JComboBox();
		rootPanel.add(comboBoxDistrict, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final JLabel label4 = new JLabel();
		label4.setText("Общ. пл., от");
		rootPanel.add(label4, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		formattedTextFieldTotalAreaFrom = new JFormattedTextField();
		rootPanel.add(formattedTextFieldTotalAreaFrom, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		final JLabel label5 = new JLabel();
		label5.setText("Общ. пл., до");
		rootPanel.add(label5, new com.intellij.uiDesigner.core.GridConstraints(1, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		formattedTextFieldTotalAreaTo = new JFormattedTextField();
		rootPanel.add(formattedTextFieldTotalAreaTo, new com.intellij.uiDesigner.core.GridConstraints(1, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		final JLabel label6 = new JLabel();
		label6.setText("Жилая пл., от");
		rootPanel.add(label6, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		formattedTextFieldLivingFrom = new JFormattedTextField();
		rootPanel.add(formattedTextFieldLivingFrom, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		final JLabel label7 = new JLabel();
		label7.setText("Жилая пл., до");
		rootPanel.add(label7, new com.intellij.uiDesigner.core.GridConstraints(2, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		formattedTextFieldLivingAreaTo = new JFormattedTextField();
		rootPanel.add(formattedTextFieldLivingAreaTo, new com.intellij.uiDesigner.core.GridConstraints(2, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		final JLabel label8 = new JLabel();
		label8.setText("Пл. кухни, от");
		rootPanel.add(label8, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		formattedTextFieldKitchenAreaFrom = new JFormattedTextField();
		rootPanel.add(formattedTextFieldKitchenAreaFrom, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		final JLabel label9 = new JLabel();
		label9.setText("Пл. кухни, до");
		rootPanel.add(label9, new com.intellij.uiDesigner.core.GridConstraints(3, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		formattedTextFieldKitchenAreaTo = new JFormattedTextField();
		rootPanel.add(formattedTextFieldKitchenAreaTo, new com.intellij.uiDesigner.core.GridConstraints(3, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		formattedTextFieldRoomsFrom = new JFormattedTextField();
		rootPanel.add(formattedTextFieldRoomsFrom, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		final JLabel label10 = new JLabel();
		label10.setText("Комнат, до");
		rootPanel.add(label10, new com.intellij.uiDesigner.core.GridConstraints(4, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		formattedTextFieldRoomsTo = new JFormattedTextField();
		rootPanel.add(formattedTextFieldRoomsTo, new com.intellij.uiDesigner.core.GridConstraints(4, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		formattedTextFieldFloorFrom = new JFormattedTextField();
		rootPanel.add(formattedTextFieldFloorFrom, new com.intellij.uiDesigner.core.GridConstraints(5, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		formattedTextFieldFloorTo = new JFormattedTextField();
		rootPanel.add(formattedTextFieldFloorTo, new com.intellij.uiDesigner.core.GridConstraints(5, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		final JLabel label11 = new JLabel();
		label11.setText("Этаж, до");
		rootPanel.add(label11, new com.intellij.uiDesigner.core.GridConstraints(5, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return rootPanel;
	}
}
